// src/constants.js

export const STATUS_COLORS = {
  Unread: 'bg-gray-700 text-gray-300',
  Blank: 'bg-red-600 text-white',
  Think: 'bg-yellow-500 text-black',
  Ready: 'bg-blue-500 text-white',
  Done: 'bg-green-600 text-white'
};

// export const PROBLEM_LISTS = {
//   'CF 1600': [
//     { id: '1985G', name: 'Placeholder Name 1' },
//     { id: '1458A', name: 'Placeholder Name 2' },
//     { id: '1542C', name: 'Placeholder Name 3' },
//     { id: '1519D', name: 'Placeholder Name 4' },
//     { id: '2085C', name: 'Placeholder Name 5' },
//     { id: '1856C', name: 'Placeholder Name 6' },
//     { id: '1364C', name: 'Placeholder Name 7' },
//     { id: '1971F', name: 'Placeholder Name 8' },
//     { id: '1753B', name: 'Placeholder Name 9' },
//     { id: '1603B', name: 'Placeholder Name 10' }
//   ],
//   'CF 1700': [
//     { id: '1325D', name: 'Placeholder Name 11' },
//     { id: '1554B', name: 'Placeholder Name 12' },
//     { id: '1512G', name: 'Placeholder Name 13' },
//     { id: '2089A', name: 'Placeholder Name 14' },
//     { id: '1770C', name: 'Placeholder Name 15' },
//     { id: '2122C', name: 'Placeholder Name 16' },
//     { id: '1485C', name: 'Placeholder Name 17' },
//     { id: '1883E', name: 'Placeholder Name 18' },
//     { id: '1879D', name: 'Placeholder Name 19' },
//     { id: '1469D', name: 'Placeholder Name 20' }
//   ],
//   'CF 1800': [
//     { id: '1295D', name: 'Placeholder Name 21' },
//     { id: '1225D', name: 'Placeholder Name 22' },
//     { id: '1691D', name: 'Placeholder Name 23' },
//     { id: '1852A', name: 'Placeholder Name 24' },
//     { id: '1552D', name: 'Placeholder Name 25' },
//     { id: '2043D', name: 'Placeholder Name 26' },
//     { id: '1554C', name: 'Placeholder Name 27' },
//     { id: '1177B', name: 'Placeholder Name 28' },
//     { id: '2121F', name: 'Placeholder Name 29' },
//     { id: '1758D', name: 'Placeholder Name 30' }
//   ],
//   'CF 1900': [
//     { id: '1400D', name: 'Placeholder Name 31' },
//     { id: '1957D', name: 'Placeholder Name 32' },
//     { id: '1492D', name: 'Placeholder Name 33' },
//     { id: '1895D', name: 'Placeholder Name 34' },
//     { id: '1656D', name: 'Placeholder Name 35' },
//     { id: '1620E', name: 'Placeholder Name 36' },
//     { id: '1205B', name: 'Placeholder Name 37' },
//     { id: '1168B', name: 'Placeholder Name 38' },
//     { id: '1986F', name: 'Placeholder Name 39' },
//     { id: '2040D', name: 'Placeholder Name 40' }
//   ]
// };
export const PROBLEM_LISTS = {
  'CF 1600': [
    { id: '797A', name: 'k-Factorization' },
    { id: '792A', name: 'New Bus Route' },
    { id: '789A', name: 'Anastasia and pebbles' },
    { id: '785B', name: 'Anton and Classes' },
    { id: '779B', name: 'Weird Rounding' },
    { id: '767A', name: 'Snacktower' },
    { id: '765B', name: 'Code obfuscation' },
    { id: '758B', name: 'Blown Garland' },
    { id: '755B', name: 'PolandBall and Game' },
    { id: '754B', name: 'Ilya and tic-tac-toe game' },
    { id: '735B', name: 'Urbanization' },
    { id: '733B', name: 'Parade' },
    { id: '731B', name: 'Coupons and Discounts' },
    { id: '723B', name: 'Text Document Analysis' },
    { id: '721B', name: 'Passwords' },
    { id: '719A', name: 'Vitya in the Countryside' },
    { id: '714A', name: 'Meeting of Old Friends' },
    { id: '712B', name: 'Memory and Trident' },
    { id: '706B', name: 'Interesting drink' },
    { id: '705B', name: 'Spider Man' },
    { id: '690A1', name: 'Collective Mindsets (easy)' },
    { id: '686B', name: "Little Robber Girl's Zoo" },
    { id: '682A', name: 'Alyona and Numbers' },
    { id: '675A', name: 'Infinite Sequence' },
    { id: '667B', name: 'Coat of Anticubism' },
    { id: '667A', name: 'Pouring Rain' },
    { id: '651A', name: 'Joysticks' },
    { id: '648C', name: 'Путь Робота' },
    { id: '638A', name: 'Home Numbers' },
    { id: '635A', name: 'Orchestra' },
    { id: '633A', name: 'Ebony and Ivory' },
    { id: '630J', name: 'Divisibility' },
    { id: '630D', name: 'Hexagons!' },
    { id: '630C', name: 'Lucky Numbers' },
    { id: '629B', name: "Far Relative's Problem" },
    { id: '624B', name: 'Making a String' },
    { id: '618B', name: 'Guess the Permutation' },
    { id: '609B', name: 'The Best Gift' },
    { id: '602A', name: 'Two Bases' },
    { id: '596B', name: 'Wilbur and Array' },
    { id: '596A', name: 'Wilbur and Swimming Pool' },
    { id: '592B', name: 'The Monster and the Squirrel' },
    { id: '581B', name: 'Luxurious Houses' },
    { id: '570A', name: 'Elections' },
    { id: '558A', name: 'Lala Land and Apple Trees' },
    { id: '557A', name: 'Ilya and Diplomas' },
    { id: '556B', name: 'Case of Fake Numbers' },
    { id: '548A', name: 'Mike and Fax' },
    { id: '545B', name: 'Equidistant String' },
    { id: '544A', name: 'Set of Strings' },
    { id: '535B', name: 'Tavas and SaDDas' },
    { id: '534A', name: 'Exam' },
    { id: '527A', name: 'Playing with Paper' }
  ],
  'CF 1700': [
    { id: '892B', name: 'Wrath' },
    { id: '879B', name: 'Table Tennis' },
    { id: '875A', name: 'Classroom Watch' },
    { id: '870B', name: 'Maximum of Maximums of Minimums' },
    { id: '854B', name: 'Maxim Buys an Apartment' },
    { id: '842A', name: 'Kirill And The Game' },
    { id: '828A', name: 'Restaurant Tables' },
    { id: '817A', name: 'Treasure Hunt' },
    { id: '812A', name: 'Sagheer and Crossroads' },
    { id: '811B', name: 'Vladik and Complicated Book' },
    { id: '803B', name: 'Distances to Zero' },
    { id: '802M1', name: "April Fools' Problem (easy)" },
    { id: '794B', name: 'Cutting Carrot' },
    { id: '787A', name: 'The Monster' },
    { id: '779C', name: 'Dishonest Sellers' },
    { id: '776B', name: 'Sherlock and his girlfriend' },
    { id: '774C', name: 'Maximum Number' },
    { id: '769B', name: 'News About Credit' },
    { id: '765C', name: 'Table Tennis Game 2' },
    { id: '754A', name: 'Lesha and array splitting' },
    { id: '749B', name: 'Parallelogram is Back' },
    { id: '743B', name: 'Chloe and the sequence' },
    { id: '743A', name: 'Vladik and flights' },
    { id: '740B', name: 'Alyona and flowers' },
    { id: '732C', name: 'Sanatorium' },
    { id: '729B', name: 'Spotlights' },
    { id: '725B', name: 'Food on the Plane' },
    { id: '722B', name: 'Verse Pattern' },
    { id: '717C', name: 'Potions Homework' },
    { id: '714B', name: 'Filya and Homework' },
    { id: '708A', name: 'Letters Cyclic Shift' },
    { id: '701B', name: 'Cells Not Under Attack' },
    { id: '690D1', name: 'The Wall (easy)' },
    { id: '683A', name: 'The Check of the Point' },
    { id: '682B', name: 'Alyona and Mex' },
    { id: '660A', name: 'Co-prime Array' },
    { id: '659C', name: 'Tanya and Toys' },
    { id: '651B', name: 'Beautiful Paintings' },
    { id: '645B', name: 'Mischievous Mess Makers' },
    { id: '645A', name: 'Amity Assessment' },
    { id: '639A', name: 'Bear and Displayed Friends' },
    { id: '637B', name: 'Chat Order' },
    { id: '632A', name: 'Grandma Laura and Apples' },
    { id: '631B', name: 'Print Check' },
    { id: '630R', name: 'Game' },
    { id: '630B', name: "Moore's Law" },
    { id: '625B', name: 'War of the Corporations' },
    { id: '612B', name: 'HDD is Outdated Technology' },
    { id: '606A', name: 'Magic Spheres' },
    { id: '593A', name: '2Char' },
    { id: '592A', name: 'PawnChess' },
    { id: '591B', name: 'Rebranding' },
    { id: '583B', name: "Robot's Task" }
  ],
  'CF 1800': [
    { id: '907A', name: 'Masha and Bears' },
    { id: '900B', name: 'Position in Fraction' },
    { id: '899C', name: 'Dividing the numbers' },
    { id: '897B', name: "Chtholly's request" },
    { id: '893C', name: 'Rumor' },
    { id: '887B', name: 'Cubes for Masha' },
    { id: '886C', name: 'Petya and Catacombs' },
    { id: '883F', name: 'Lost in Transliteration' },
    { id: '876B', name: 'Divisibility of Differences' },
    { id: '870C', name: 'Maximum splitting' },
    { id: '862B', name: 'Mahmoud and Ehab and the bipartiteness' },
    { id: '844B', name: 'Rectangles' },
    { id: '840A', name: 'Leha and Function' },
    { id: '828B', name: 'Black Square' },
    { id: '821B', name: 'Okabe and Banana Trees' },
    { id: '820B', name: 'Mister B and Angle in Polygon' },
    { id: '814B', name: 'An express train to reveries' },
    { id: '810B', name: 'Summer sell-off' },
    { id: '808B', name: 'Average Sleep Time' },
    { id: '807B', name: 'T-Shirt Hunt' },
    { id: '798B', name: 'Mike and strings' },
    { id: '796B', name: 'Find The Bone' },
    { id: '792B', name: 'Counting-out Rhyme' },
    { id: '787B', name: 'Not Afraid' },
    { id: '777B', name: 'Game of Credit Cards' },
    { id: '770B', name: 'Maximize Sum of Digits' },
    { id: '761B', name: 'Dasha and friends' },
    { id: '755C', name: 'PolandBall and Forest' },
    { id: '750B', name: 'New Year and North Pole' },
    { id: '747C', name: 'Servers' },
    { id: '740A', name: 'Alyona and copybooks' },
    { id: '730H', name: 'Delete Them' },
    { id: '722A', name: 'Broken Clock' },
    { id: '716B', name: 'Complete the Word' },
    { id: '707B', name: 'Bakery' },
    { id: '690F1', name: 'Tree of Life (easy)' },
    { id: '690C1', name: 'Brain Network (easy)' },
    { id: '681B', name: 'Economy Game' },
    { id: '673B', name: 'Problems for Round' },
    { id: '670C', name: 'Cinema' },
    { id: '665C', name: 'Simple Strings' },
    { id: '661A', name: 'Lazy Caterer Sequence' },
    { id: '659B', name: 'Qualifying Contest' },
    { id: '653B', name: 'Bear and Compressing' },
    { id: '634A', name: 'Island Puzzle' },
    { id: '633B', name: 'A Trivial Problem' },
    { id: '630N', name: 'Forecast' },
    { id: '630F', name: 'Selection of Personnel' },
    { id: '628C', name: 'Bear and String Distance' },
    { id: '628B', name: 'New Skateboard' },
    { id: '626B', name: 'Cards' },
    { id: '625C', name: 'K-special Tables' },
    { id: '621B', name: 'Wet Shark and Bishops' }
  ],
  'CF 1900': [
    { id: '838A', name: 'Binary Blocks' },
    { id: '816B', name: 'Karen and Coffee' },
    { id: '808C', name: 'Tea Party' },
    { id: '804B', name: 'Minimum number of steps' },
    { id: '803A', name: 'Maximal Binary Matrix' },
    { id: '802J1', name: 'Send the Fool Further! (easy)' },
    { id: '799B', name: 'T-shirt buying' },
    { id: '797B', name: 'Odd sum' },
    { id: '770D', name: 'Draw Brackets!' },
    { id: '762B', name: 'USB vs. PS/2' },
    { id: '762A', name: 'k-th divisor' },
    { id: '757B', name: "Bash's Big Day" },
    { id: '748C', name: 'Santa Claus and Robot' },
    { id: '745B', name: 'Hongcow Solves A Puzzle' },
    { id: '727C', name: 'Guess the Array' },
    { id: '719B', name: 'Anatoly and Cockroaches' },
    { id: '713A', name: 'Sonya and Queries' },
    { id: '711B', name: 'Chris and Magic Square' },
    { id: '710B', name: 'Optimal Point on a Line' },
    { id: '703B', name: 'Mishka and trip' },
    { id: '699B', name: 'One Bomb' },
    { id: '698A', name: 'Vacations' },
    { id: '697B', name: 'Barnicle' },
    { id: '689A', name: 'Mike and Cellphone' },
    { id: '683D', name: 'Chocolate Bar' },
    { id: '679A', name: 'Bear and Prime 100' },
    { id: '677B', name: 'Vanya and Food Processor' },
    { id: '675B', name: 'Restoring Painting' },
    { id: '670D1', name: 'Magic Powder - 1' },
    { id: '665B', name: 'Shopping' },
    { id: '652A', name: 'Gabriel and Caterpillar' },
    { id: '650A', name: 'Watchmen' },
    { id: '649B', name: 'Этажи' },
    { id: '641B', name: 'Little Artem and Matrix' },
    { id: '637C', name: 'Promocodes with Mistakes' },
    { id: '632B', name: 'Alice, Bob, Two Teams' },
    { id: '630L', name: 'Cracking the Code' },
    { id: '630H', name: 'Benches' },
    { id: '614B', name: "Gena's Code" },
    { id: '612C', name: 'Replace To Make Regular Bracket Sequence' },
    { id: '604B', name: 'More Cowbell' },
    { id: '602B', name: 'Approximating a Constant Range' },
    { id: '581C', name: 'Developing Skills' },
    { id: '550B', name: 'Preparing Olympiad' },
    { id: '548B', name: 'Mike and Fun' },
    { id: '546C', name: 'Soldier and Cards' },
    { id: '544B', name: 'Sea and Islands' },
    { id: '538B', name: 'Quasi Binary' },
    { id: '538A', name: 'Cutting Banner' },
    { id: '534B', name: 'Covered Path' },
    { id: '526B', name: 'Om Nom and Dark Park' },
    { id: '525B', name: 'Pasha and String' },
    { id: '523C', name: 'Name Quest' }
  ]
};