// src/constants.js

export const STATUS_COLORS = {
  Unread: 'bg-gray-700 text-gray-300',
  Blank: 'bg-red-600 text-white',
  Think: 'bg-yellow-500 text-black',
  Ready: 'bg-blue-500 text-white',
  Done: 'bg-green-600 text-white'
};

// export const PROBLEM_LISTS = {
//   'CF 1600': [
//     { id: '1985G', name: 'Placeholder Name 1' },
//     { id: '1458A', name: 'Placeholder Name 2' },
//     { id: '1542C', name: 'Placeholder Name 3' },
//     { id: '1519D', name: 'Placeholder Name 4' },
//     { id: '2085C', name: 'Placeholder Name 5' },
//     { id: '1856C', name: 'Placeholder Name 6' },
//     { id: '1364C', name: 'Placeholder Name 7' },
//     { id: '1971F', name: 'Placeholder Name 8' },
//     { id: '1753B', name: 'Placeholder Name 9' },
//     { id: '1603B', name: 'Placeholder Name 10' }
//   ],
//   'CF 1700': [
//     { id: '1325D', name: 'Placeholder Name 11' },
//     { id: '1554B', name: 'Placeholder Name 12' },
//     { id: '1512G', name: 'Placeholder Name 13' },
//     { id: '2089A', name: 'Placeholder Name 14' },
//     { id: '1770C', name: 'Placeholder Name 15' },
//     { id: '2122C', name: 'Placeholder Name 16' },
//     { id: '1485C', name: 'Placeholder Name 17' },
//     { id: '1883E', name: 'Placeholder Name 18' },
//     { id: '1879D', name: 'Placeholder Name 19' },
//     { id: '1469D', name: 'Placeholder Name 20' }
//   ],
//   'CF 1800': [
//     { id: '1295D', name: 'Placeholder Name 21' },
//     { id: '1225D', name: 'Placeholder Name 22' },
//     { id: '1691D', name: 'Placeholder Name 23' },
//     { id: '1852A', name: 'Placeholder Name 24' },
//     { id: '1552D', name: 'Placeholder Name 25' },
//     { id: '2043D', name: 'Placeholder Name 26' },
//     { id: '1554C', name: 'Placeholder Name 27' },
//     { id: '1177B', name: 'Placeholder Name 28' },
//     { id: '2121F', name: 'Placeholder Name 29' },
//     { id: '1758D', name: 'Placeholder Name 30' }
//   ],
//   'CF 1900': [
//     { id: '1400D', name: 'Placeholder Name 31' },
//     { id: '1957D', name: 'Placeholder Name 32' },
//     { id: '1492D', name: 'Placeholder Name 33' },
//     { id: '1895D', name: 'Placeholder Name 34' },
//     { id: '1656D', name: 'Placeholder Name 35' },
//     { id: '1620E', name: 'Placeholder Name 36' },
//     { id: '1205B', name: 'Placeholder Name 37' },
//     { id: '1168B', name: 'Placeholder Name 38' },
//     { id: '1986F', name: 'Placeholder Name 39' },
//     { id: '2040D', name: 'Placeholder Name 40' }
//   ]
// };
// export const PROBLEM_LISTS = {
//   'CF 1600': [
//     { id: '797A', name: 'k-Factorization' },
//     { id: '792A', name: 'New Bus Route' },
//     { id: '789A', name: 'Anastasia and pebbles' },
//     { id: '785B', name: 'Anton and Classes' },
//     { id: '779B', name: 'Weird Rounding' },
//     { id: '767A', name: 'Snacktower' },
//     { id: '765B', name: 'Code obfuscation' },
//     { id: '758B', name: 'Blown Garland' },
//     { id: '755B', name: 'PolandBall and Game' },
//     { id: '754B', name: 'Ilya and tic-tac-toe game' },
//     { id: '735B', name: 'Urbanization' },
//     { id: '733B', name: 'Parade' },
//     { id: '731B', name: 'Coupons and Discounts' },
//     { id: '723B', name: 'Text Document Analysis' },
//     { id: '721B', name: 'Passwords' },
//     { id: '719A', name: 'Vitya in the Countryside' },
//     { id: '714A', name: 'Meeting of Old Friends' },
//     { id: '712B', name: 'Memory and Trident' },
//     { id: '706B', name: 'Interesting drink' },
//     { id: '705B', name: 'Spider Man' },
//     { id: '690A1', name: 'Collective Mindsets (easy)' },
//     { id: '686B', name: "Little Robber Girl's Zoo" },
//     { id: '682A', name: 'Alyona and Numbers' },
//     { id: '675A', name: 'Infinite Sequence' },
//     { id: '667B', name: 'Coat of Anticubism' },
//     { id: '667A', name: 'Pouring Rain' },
//     { id: '651A', name: 'Joysticks' },
//     { id: '648C', name: 'Путь Робота' },
//     { id: '638A', name: 'Home Numbers' },
//     { id: '635A', name: 'Orchestra' },
//     { id: '633A', name: 'Ebony and Ivory' },
//     { id: '630J', name: 'Divisibility' },
//     { id: '630D', name: 'Hexagons!' },
//     { id: '630C', name: 'Lucky Numbers' },
//     { id: '629B', name: "Far Relative's Problem" },
//     { id: '624B', name: 'Making a String' },
//     { id: '618B', name: 'Guess the Permutation' },
//     { id: '609B', name: 'The Best Gift' },
//     { id: '602A', name: 'Two Bases' },
//     { id: '596B', name: 'Wilbur and Array' },
//     { id: '596A', name: 'Wilbur and Swimming Pool' },
//     { id: '592B', name: 'The Monster and the Squirrel' },
//     { id: '581B', name: 'Luxurious Houses' },
//     { id: '570A', name: 'Elections' },
//     { id: '558A', name: 'Lala Land and Apple Trees' },
//     { id: '557A', name: 'Ilya and Diplomas' },
//     { id: '556B', name: 'Case of Fake Numbers' },
//     { id: '548A', name: 'Mike and Fax' },
//     { id: '545B', name: 'Equidistant String' },
//     { id: '544A', name: 'Set of Strings' },
//     { id: '535B', name: 'Tavas and SaDDas' },
//     { id: '534A', name: 'Exam' },
//     { id: '527A', name: 'Playing with Paper' }
//   ],
//   'CF 1700': [
//     { id: '892B', name: 'Wrath' },
//     { id: '879B', name: 'Table Tennis' },
//     { id: '875A', name: 'Classroom Watch' },
//     { id: '870B', name: 'Maximum of Maximums of Minimums' },
//     { id: '854B', name: 'Maxim Buys an Apartment' },
//     { id: '842A', name: 'Kirill And The Game' },
//     { id: '828A', name: 'Restaurant Tables' },
//     { id: '817A', name: 'Treasure Hunt' },
//     { id: '812A', name: 'Sagheer and Crossroads' },
//     { id: '811B', name: 'Vladik and Complicated Book' },
//     { id: '803B', name: 'Distances to Zero' },
//     { id: '802M1', name: "April Fools' Problem (easy)" },
//     { id: '794B', name: 'Cutting Carrot' },
//     { id: '787A', name: 'The Monster' },
//     { id: '779C', name: 'Dishonest Sellers' },
//     { id: '776B', name: 'Sherlock and his girlfriend' },
//     { id: '774C', name: 'Maximum Number' },
//     { id: '769B', name: 'News About Credit' },
//     { id: '765C', name: 'Table Tennis Game 2' },
//     { id: '754A', name: 'Lesha and array splitting' },
//     { id: '749B', name: 'Parallelogram is Back' },
//     { id: '743B', name: 'Chloe and the sequence' },
//     { id: '743A', name: 'Vladik and flights' },
//     { id: '740B', name: 'Alyona and flowers' },
//     { id: '732C', name: 'Sanatorium' },
//     { id: '729B', name: 'Spotlights' },
//     { id: '725B', name: 'Food on the Plane' },
//     { id: '722B', name: 'Verse Pattern' },
//     { id: '717C', name: 'Potions Homework' },
//     { id: '714B', name: 'Filya and Homework' },
//     { id: '708A', name: 'Letters Cyclic Shift' },
//     { id: '701B', name: 'Cells Not Under Attack' },
//     { id: '690D1', name: 'The Wall (easy)' },
//     { id: '683A', name: 'The Check of the Point' },
//     { id: '682B', name: 'Alyona and Mex' },
//     { id: '660A', name: 'Co-prime Array' },
//     { id: '659C', name: 'Tanya and Toys' },
//     { id: '651B', name: 'Beautiful Paintings' },
//     { id: '645B', name: 'Mischievous Mess Makers' },
//     { id: '645A', name: 'Amity Assessment' },
//     { id: '639A', name: 'Bear and Displayed Friends' },
//     { id: '637B', name: 'Chat Order' },
//     { id: '632A', name: 'Grandma Laura and Apples' },
//     { id: '631B', name: 'Print Check' },
//     { id: '630R', name: 'Game' },
//     { id: '630B', name: "Moore's Law" },
//     { id: '625B', name: 'War of the Corporations' },
//     { id: '612B', name: 'HDD is Outdated Technology' },
//     { id: '606A', name: 'Magic Spheres' },
//     { id: '593A', name: '2Char' },
//     { id: '592A', name: 'PawnChess' },
//     { id: '591B', name: 'Rebranding' },
//     { id: '583B', name: "Robot's Task" }
//   ],
//   'CF 1800': [
//     { id: '907A', name: 'Masha and Bears' },
//     { id: '900B', name: 'Position in Fraction' },
//     { id: '899C', name: 'Dividing the numbers' },
//     { id: '897B', name: "Chtholly's request" },
//     { id: '893C', name: 'Rumor' },
//     { id: '887B', name: 'Cubes for Masha' },
//     { id: '886C', name: 'Petya and Catacombs' },
//     { id: '883F', name: 'Lost in Transliteration' },
//     { id: '876B', name: 'Divisibility of Differences' },
//     { id: '870C', name: 'Maximum splitting' },
//     { id: '862B', name: 'Mahmoud and Ehab and the bipartiteness' },
//     { id: '844B', name: 'Rectangles' },
//     { id: '840A', name: 'Leha and Function' },
//     { id: '828B', name: 'Black Square' },
//     { id: '821B', name: 'Okabe and Banana Trees' },
//     { id: '820B', name: 'Mister B and Angle in Polygon' },
//     { id: '814B', name: 'An express train to reveries' },
//     { id: '810B', name: 'Summer sell-off' },
//     { id: '808B', name: 'Average Sleep Time' },
//     { id: '807B', name: 'T-Shirt Hunt' },
//     { id: '798B', name: 'Mike and strings' },
//     { id: '796B', name: 'Find The Bone' },
//     { id: '792B', name: 'Counting-out Rhyme' },
//     { id: '787B', name: 'Not Afraid' },
//     { id: '777B', name: 'Game of Credit Cards' },
//     { id: '770B', name: 'Maximize Sum of Digits' },
//     { id: '761B', name: 'Dasha and friends' },
//     { id: '755C', name: 'PolandBall and Forest' },
//     { id: '750B', name: 'New Year and North Pole' },
//     { id: '747C', name: 'Servers' },
//     { id: '740A', name: 'Alyona and copybooks' },
//     { id: '730H', name: 'Delete Them' },
//     { id: '722A', name: 'Broken Clock' },
//     { id: '716B', name: 'Complete the Word' },
//     { id: '707B', name: 'Bakery' },
//     { id: '690F1', name: 'Tree of Life (easy)' },
//     { id: '690C1', name: 'Brain Network (easy)' },
//     { id: '681B', name: 'Economy Game' },
//     { id: '673B', name: 'Problems for Round' },
//     { id: '670C', name: 'Cinema' },
//     { id: '665C', name: 'Simple Strings' },
//     { id: '661A', name: 'Lazy Caterer Sequence' },
//     { id: '659B', name: 'Qualifying Contest' },
//     { id: '653B', name: 'Bear and Compressing' },
//     { id: '634A', name: 'Island Puzzle' },
//     { id: '633B', name: 'A Trivial Problem' },
//     { id: '630N', name: 'Forecast' },
//     { id: '630F', name: 'Selection of Personnel' },
//     { id: '628C', name: 'Bear and String Distance' },
//     { id: '628B', name: 'New Skateboard' },
//     { id: '626B', name: 'Cards' },
//     { id: '625C', name: 'K-special Tables' },
//     { id: '621B', name: 'Wet Shark and Bishops' }
//   ],
//   'CF 1900': [
//     { id: '838A', name: 'Binary Blocks' },
//     { id: '816B', name: 'Karen and Coffee' },
//     { id: '808C', name: 'Tea Party' },
//     { id: '804B', name: 'Minimum number of steps' },
//     { id: '803A', name: 'Maximal Binary Matrix' },
//     { id: '802J1', name: 'Send the Fool Further! (easy)' },
//     { id: '799B', name: 'T-shirt buying' },
//     { id: '797B', name: 'Odd sum' },
//     { id: '770D', name: 'Draw Brackets!' },
//     { id: '762B', name: 'USB vs. PS/2' },
//     { id: '762A', name: 'k-th divisor' },
//     { id: '757B', name: "Bash's Big Day" },
//     { id: '748C', name: 'Santa Claus and Robot' },
//     { id: '745B', name: 'Hongcow Solves A Puzzle' },
//     { id: '727C', name: 'Guess the Array' },
//     { id: '719B', name: 'Anatoly and Cockroaches' },
//     { id: '713A', name: 'Sonya and Queries' },
//     { id: '711B', name: 'Chris and Magic Square' },
//     { id: '710B', name: 'Optimal Point on a Line' },
//     { id: '703B', name: 'Mishka and trip' },
//     { id: '699B', name: 'One Bomb' },
//     { id: '698A', name: 'Vacations' },
//     { id: '697B', name: 'Barnicle' },
//     { id: '689A', name: 'Mike and Cellphone' },
//     { id: '683D', name: 'Chocolate Bar' },
//     { id: '679A', name: 'Bear and Prime 100' },
//     { id: '677B', name: 'Vanya and Food Processor' },
//     { id: '675B', name: 'Restoring Painting' },
//     { id: '670D1', name: 'Magic Powder - 1' },
//     { id: '665B', name: 'Shopping' },
//     { id: '652A', name: 'Gabriel and Caterpillar' },
//     { id: '650A', name: 'Watchmen' },
//     { id: '649B', name: 'Этажи' },
//     { id: '641B', name: 'Little Artem and Matrix' },
//     { id: '637C', name: 'Promocodes with Mistakes' },
//     { id: '632B', name: 'Alice, Bob, Two Teams' },
//     { id: '630L', name: 'Cracking the Code' },
//     { id: '630H', name: 'Benches' },
//     { id: '614B', name: "Gena's Code" },
//     { id: '612C', name: 'Replace To Make Regular Bracket Sequence' },
//     { id: '604B', name: 'More Cowbell' },
//     { id: '602B', name: 'Approximating a Constant Range' },
//     { id: '581C', name: 'Developing Skills' },
//     { id: '550B', name: 'Preparing Olympiad' },
//     { id: '548B', name: 'Mike and Fun' },
//     { id: '546C', name: 'Soldier and Cards' },
//     { id: '544B', name: 'Sea and Islands' },
//     { id: '538B', name: 'Quasi Binary' },
//     { id: '538A', name: 'Cutting Banner' },
//     { id: '534B', name: 'Covered Path' },
//     { id: '526B', name: 'Om Nom and Dark Park' },
//     { id: '525B', name: 'Pasha and String' },
//     { id: '523C', name: 'Name Quest' }
//   ]
// };

export const PROBLEM_LISTS = {
  'CF 1600': [
    { id: '6B', name: "President's Office" },
    { id: '12B', name: "Correct Solution?" },
    { id: '12C', name: "Fruits" },
    { id: '25B', name: "Phone numbers" },
    { id: '39D', name: "Cubical Planet" },
    { id: '43B', name: "Letter" },
    { id: '53A', name: "Autocomplete" },
    { id: '82A', name: "Double Cola" },
    { id: '100A', name: "Carpeting the Room" },
    { id: '162A', name: "Pentagonal numbers" },
    { id: '186A', name: "Comparing Strings" },
    { id: '188A', name: "Hexagonal Numbers" },
    { id: '188D', name: "Asterisks" },
    { id: '224A', name: "Parallelepiped" },
    { id: '270A', name: "Fancy Fence" },
    { id: '296A', name: "Yaroslav and Permutations" },
    { id: '300A', name: "Array" },
    { id: '312A', name: "Whose sentence is it?" },
    { id: '349A', name: "Cinema Line" },
    { id: '362B', name: "Petya and Staircases" },
    { id: '365A', name: "Good Number" },
    { id: '382A', name: "Ksenia and Pan Scales" },
    { id: '433A', name: "Kitahara Haruki's Gift" },
    { id: '456A', name: "Laptops" },
    { id: '475A', name: "Bayan Bus" },
    { id: '501B', name: "Misha and Changing Handles" },
    { id: '534A', name: "Exam" },
    { id: '596A', name: "Wilbur and Swimming Pool" },
    { id: '630C', name: "Lucky Numbers" },
    { id: '630J', name: "Divisibility" },
    { id: '755B', name: "PolandBall and Game" },
    { id: '797A', name: "k-Factorization" },
    { id: '825A', name: "Binary Protocol" },
    { id: '835B', name: "The number on the board" },
    { id: '841B', name: "Godsend" },
    { id: '858A', name: "k-rounding" },
    { id: '877A', name: "Alex and broken contest" },
    { id: '911A', name: "Nearest Minimums" },
    { id: '919B', name: "Perfect Number" },
    { id: '1001A', name: "Generate plus state or minus state" },
    { id: '1060B', name: "Maximum Sum of Digits" },
    { id: '1115G1', name: "AND oracle" },
    { id: '1117A', name: "Best Subsegment" },
    { id: '1213B', name: "Bad Prices" },
    { id: '1288B', name: "Yet Another Meme Problem" },
    { id: '1327A', name: "Sum of Odd Integers" },
    { id: '1366A', name: "Shovels and Swords" },
    { id: '1478B', name: "Nezzar and Lucky Number" },
    { id: '1490C', name: "Sum of Cubes" },
    { id: '1511B', name: "GCD Length" },
    { id: '1593D1', name: "All are Same" },
    { id: '1594B', name: "Special Numbers" },
    { id: '1618C', name: "Paint the Array" },
    { id: '1638B', name: "Odd Swap Sort" },
    { id: '1656B', name: "Subtract Operation" },
    { id: '1672C', name: "Unequal Array" },
    { id: '1700B', name: "Palindromic Numbers" },
    { id: '1708B', name: "Difference of GCDs" },
    { id: '1712C', name: "Sort Zero" },
    { id: '1739B', name: "Array Recovery" },
    { id: '1783B', name: "Matrix of Differences" },
    { id: '1821B', name: "Sort the Subarray" },
    { id: '1827A', name: "Counting Orders" },
    { id: '1829E', name: "The Lakes" },
    { id: '1840B', name: "Binary Cafe" },
    { id: '1899C', name: "Yarik and Array" },
    { id: '1950D', name: "Product of Binary Decimals" },
    { id: '1976B', name: "Increase/Decrease/Copy" },
    { id: '1977B', name: "Binary Colouring" },
    { id: '1984B', name: "Large Addition" },
    { id: '1999D', name: "Slavic's Exam" },
    { id: '2025B', name: "Binomial Coefficients, Kind Of" },
    { id: '2036C', name: "Anya and 1100" },
    { id: '2043B', name: "Digits" },
    { id: '2050B', name: "Transfusion" },
    { id: '2060D', name: "Subtract Min Sort" },
    { id: '2084B', name: "MIN = GCD" },
    { id: '2137C', name: "Maximum Even Sum" },
    { id: '2179C', name: "Blackslex and Number Theory" }
  ],
  'CF 1700': [
    { id: '5B', name: "Center Alignment" },
    { id: '6C', name: "Alice, Bob and Chocolate" },
    { id: '9C', name: "Hexadecimal's Numbers" },
    { id: '18C', name: "Stripe" },
    { id: '23A', name: "You're Given a String..." },
    { id: '27A', name: "Next Test" },
    { id: '31A', name: "Worms Evolution" },
    { id: '38B', name: "Chess" },
    { id: '47B', name: "Coins" },
    { id: '53C', name: "Little Frog" },
    { id: '55A', name: "Flea travel" },
    { id: '59B', name: "Fortune Telling" },
    { id: '78B', name: "Easter Eggs" },
    { id: '134A', name: "Average Numbers" },
    { id: '217A', name: "Ice Skating" },
    { id: '239A', name: "Two Bags of Potatoes" },
    { id: '254A', name: "Cards with Numbers" },
    { id: '454B', name: "Little Pony and Sort by Shift" },
    { id: '459A', name: "Pashmak and Garden" },
    { id: '466A', name: "Cheap Travel" },
    { id: '489A', name: "SwapSort" },
    { id: '489B', name: "BerSU Ball" },
    { id: '514A', name: "Chewbacca and Number" },
    { id: '523A', name: "Rotate, Flip and Zoom" },
    { id: '552B', name: "Vanya and Books" },
    { id: '554B', name: "Ohana Cleans Up" },
    { id: '630B', name: "Moore's Law" },
    { id: '630R', name: "Game" },
    { id: '660A', name: "Co-prime Array" },
    { id: '683A', name: "The Check of the Point" },
    { id: '749B', name: "Parallelogram is Back" },
    { id: '754A', name: "Lesha and array splitting" },
    { id: '765C', name: "Table Tennis Game 2" },
    { id: '802M', name: "April Fools' Problem (easy)" },
    { id: '802M1', name: "April Fools' Problem (easy)" },
    { id: '803B', name: "Distances to Zero" },
    { id: '842A', name: "Kirill And The Game" },
    { id: '892B', name: "Wrath" },
    { id: '977C', name: "Less or Equal" },
    { id: '982A', name: "Row" },
    { id: '999C', name: "Alphabetic Removals" },
    { id: '1001H', name: "Oracle for f(x) = parity of the number of 1s in x" },
    { id: '1028B', name: "Unnatural Conditions" },
    { id: '1068B', name: "LCM" },
    { id: '1076B', name: "Divisor Subtraction" },
    { id: '1104B', name: "Game with string" },
    { id: '1143B', name: "Nirvana" },
    { id: '1174B', name: "Ehab Is an Odd Person" },
    { id: '1203B', name: "Equal Rectangles" },
    { id: '1213C', name: "Book Reading" },
    { id: '1315C', name: "Restoring Permutation" },
    { id: '1352B', name: "Same Parity Summands" },
    { id: '1352C', name: "K-th Not Divisible by n" },
    { id: '1363A', name: "Odd Selection" },
    { id: '1364A', name: "XXXXX" },
    { id: '1406B', name: "Maximum Product" },
    { id: '1433D', name: "Districts Connection" },
    { id: '1497C1', name: "k-LCM (easy version)" },
    { id: '1512D', name: "Corrupted Array" },
    { id: '1514B', name: "AND 0, Sum Big" },
    { id: '1520D', name: "Same Differences" },
    { id: '1541B', name: "Pleasant Pairs" },
    { id: '1581B', name: "Diameter of Graph" },
    { id: '1608B', name: "Build the Permutation" },
    { id: '1635C', name: "Differential Sorting" },
    { id: '1656C', name: "Make Equal With Mod" },
    { id: '1669G', name: "Fall Down" },
    { id: '1681C', name: "Double Sort" },
    { id: '1736B', name: "Playing with GCD" },
    { id: '1822D', name: "Super-Permutation" },
    { id: '1826A', name: "Trust Nobody" },
    { id: '1832C', name: "Contrast Value" },
    { id: '1903B', name: "StORage room" }
  ],
  'CF 1800': [
    { id: '40A', name: "Find Color" },
    { id: '57A', name: "Square Earth?" },
    { id: '58B', name: "Coins" },
    { id: '64A', name: "Factorial" },
    { id: '94B', name: "Friends" },
    { id: '135A', name: "Replacement" },
    { id: '147A', name: "Punctuation" },
    { id: '181B', name: "Number of Triplets" },
    { id: '188B', name: "A + Reverse B" },
    { id: '189A', name: "Cut Ribbon" },
    { id: '203B', name: "Game on Paper" },
    { id: '221B', name: "Little Elephant and Numbers" },
    { id: '230B', name: "T-primes" },
    { id: '251A', name: "Points on Line" },
    { id: '276B', name: "Little Girl and Game" },
    { id: '312B', name: "Archer" },
    { id: '485B', name: "Valuable Resources" },
    { id: '493A', name: "Vasya and Football" },
    { id: '573A', name: "Bear and Poker" },
    { id: '600B', name: "Queries about less or equal elements" },
    { id: '630F', name: "Selection of Personnel" },
    { id: '630N', name: "Forecast" },
    { id: '661A', name: "Lazy Caterer Sequence" },
    { id: '665C', name: "Simple Strings" },
    { id: '770B', name: "Maximize Sum of Digits" },
    { id: '844B', name: "Rectangles" },
    { id: '876B', name: "Divisibility of Differences" },
    { id: '887B', name: "Cubes for Masha" },
    { id: '965B', name: "Battleship" },
    { id: '1001F', name: "Distinguish multi-qubit basis states" },
    { id: '1016B', name: "Segment Occurrences" },
    { id: '1029A', name: "Many Equal Substrings" },
    { id: '1030C', name: "Vasya and Golden Ticket" },
    { id: '1076C', name: "Meme Problem" },
    { id: '1157B', name: "Long Number" },
    { id: '1165C', name: "Good String" },
    { id: '1174C', name: "Ehab and a Special Coloring Problem" },
    { id: '1203C', name: "Common Divisors" },
    { id: '1220B', name: "Multiplication Table" },
    { id: '1260B', name: "Obtain Two Zeroes" },
    { id: '1294C', name: "Product of Three Numbers" },
    { id: '1373C', name: "Pluses and Minuses" },
    { id: '1422B', name: "Nice Matrix" },
    { id: '1424G', name: "Years" },
    { id: '1454D', name: "Number into Sequence" },
    { id: '1667A', name: "Make it Increasing" },
    { id: '1703F', name: "Yet Another Problem About Pairs Satisfying an Inequality" },
    { id: '1788C', name: "Matching Numbers" },
    { id: '1913C', name: "Game with Multiset" },
    { id: '1927D', name: "Find the Different Ones!" },
    { id: '1988C', name: "Increasing Sequence with Fixed OR" },
    { id: '1999E', name: "Triple Operations" },
    { id: '2033D', name: "Kousuke's Assignment" },
    { id: '2044E', name: "Insane Problem" },
    { id: '2050D', name: "Digital string maximization" },
    { id: '2169C', name: "Range Operation" }
  ],
  'CF 1900': [
    { id: '24A', name: "Ring road" },
    { id: '26B', name: "Regular Bracket Sequence" },
    { id: '41B', name: "Martian Dollar" },
    { id: '44E', name: "Anfisa the Monkey" },
    { id: '45I', name: "TCMCF+++" },
    { id: '100C', name: "A+B" },
    { id: '111A', name: "Petya and Inequiations" },
    { id: '124B', name: "Permutations" },
    { id: '125A', name: "Measuring Lengths in Baden" },
    { id: '130B', name: "Gnikool Ssalg" },
    { id: '131C', name: "The World is a Theatre" },
    { id: '180C', name: "Letter" },
    { id: '188C', name: "LCM" },
    { id: '188F', name: "Binary Notation" },
    { id: '219B', name: "Special Offer! Super Price 999 Bourles!" },
    { id: '245E', name: "Mishap in Club" },
    { id: '248B', name: "Chilly Willy" },
    { id: '260A', name: "Adding Digits" },
    { id: '289B', name: "Polo the Penguin and Matrix" },
    { id: '315A', name: "Sereja and Bottles" },
    { id: '379C', name: "New Year Ratings Change" },
    { id: '435B', name: "Pasha Maximizes" },
    { id: '470A', name: "Crystal Ball Sequence" },
    { id: '489C', name: "Given Length and Sum of Digits..." },
    { id: '513B1', name: "Permutations" },
    { id: '520B', name: "Two Buttons" },
    { id: '538B', name: "Quasi Binary" },
    { id: '544B', name: "Sea and Islands" },
    { id: '630H', name: "Benches" },
    { id: '683D', name: "Chocolate Bar" },
    { id: '699B', name: "One Bomb" },
    { id: '710B', name: "Optimal Point on a Line" },
    { id: '762A', name: "k-th divisor" },
    { id: '797B', name: "Odd sum" },
    { id: '803A', name: "Maximal Binary Matrix" },
    { id: '888C', name: "K-Dominant Character" },
    { id: '1001D', name: "Distinguish plus state and minus state" },
    { id: '1001G', name: "Oracle for f(x) = k-th element of x" },
    { id: '1046C', name: "Space Formula" },
    { id: '1057B', name: "DDoS" },
    { id: '1095C', name: "Powers Of Two" },
    { id: '1131B', name: "Draw!" },
    { id: '1167C', name: "News Distribution" },
    { id: '1215B', name: "The Number of Products" },
    { id: '1285C', name: "Fadi and LCM" },
    { id: '1324D', name: "Pair of Topics" },
    { id: '1351C', name: "Skier" },
    { id: '1354C1', name: "Simple Polygon Embedding" },
    { id: '1355D', name: "Game With Array" },
    { id: '1380C', name: "Create The Teams" },
    { id: '1463B', name: "Find The Array" },
    { id: '1494B', name: "Berland Crossword" },
    { id: '1506D', name: "Epic Transformation" },
    { id: '1526B', name: "I Hate 1111" },
    { id: '1579D', name: "Productive Meeting" },
    { id: '1606C', name: "Banknotes" },
    { id: '1697C', name: "awoo's Favorite Problem" },
    { id: '1749C', name: "Number Game" },
    { id: '1772D', name: "Absolute Sorting" },
    { id: '1790E', name: "Vlad and a Pair of Numbers" },
    { id: '1838C', name: "No Prime Differences" },
    { id: '1895C', name: "Torn Lucky Ticket" },
    { id: '1918C', name: "XOR-distance" },
    { id: '1923C', name: "Find B" },
    { id: '1965A', name: "Everything Nim" },
    { id: '1967B1', name: "Reverse Card (Easy Version)" },
    { id: '1989C', name: "Two Movies" },
    { id: '2009D', name: "Satyam and Counting" },
    { id: '2009E', name: "Klee's SUPER DUPER LARGE Array!!!" },
    { id: '2020C', name: "Bitwise Balancing" },
    { id: '2038C', name: "DIY" }
  ]
};